name: Update Contributors Data

on:
  schedule:
    # Run every week on Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allow manual trigger
  push:
    paths:
      - '.github/workflows/update-contributors.yml'

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Update contributors data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python .github/scripts/update_contributors.py
        
    - name: Update README with contributors
      run: |
        python .github/scripts/update_readme_contributors.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/contributors.json README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update contributors data and README [skip ci]"
        git push 